### ISSUE TITLE
Create an Auto invite to the organization. 

### ISSUE THREAD

**Issue by sanjay-kv** [Recode-Hive/Stackoverflow-Analysis#113]
Join the Recode Hive GitHub Org by raising an [issue](you will receive an invitation on mail) 
https://github.com/Recode-Hive
Let me know any further queries on this. 

Refer the sample.

**Comment by sanjay-kv** [comment]
@Asymtode712 I merged all PR in this repo. can you work on this?

**Comment by Asymtode712** [comment]
@sanjay-kv Sure, please assign me

**Comment by sanjay-kv** [comment]
after this let me know any good github actions to improve overall organisation outlook I will assign those to you in level 2

**Comment by Asymtode712** [comment]
Sure, PM😉

**Comment by Asymtode712** [comment]
@sanjay-kv I'm done with the creation of the workflow and template files just wanted to remind you once you will merge this file the people who would raise the issue to join the community would get added into the organization's member list which currently you and @okaditya84 are part of, so should i proceed with the PR?

**Comment by sanjay-kv** [comment]
@Asymtode712 They won't be having merge access right? If then it's fine.

**Comment by sanjay-kv** [comment]
Small change: Currently when people open issue its opening in Stack overflow repo which can create conflicts with other issues. 
So I created new repo called support. 

Can the issue raise go there. If you want to create new issue under gssoc you can do that. else this issue will do.

**Comment by Asymtode712** [comment]
Sure, I will transfer it to support repo. No need for creating another issue

**Comment by Asymtode712** [comment]
@sanjay-kv Before that, you will have to create a PAT (Personal Access Token) and assign it to INVITE_TOKEN so that the workflow can run

**Comment by Asymtode712** [comment]
@sanjay-kv also you must create a new label by the name "invite me to the community", only then the label can be assigned to an issue while creating it

**Comment by Asymtode712** [comment]
@sanjay-kv I tested the new workflow file and came to the conclusion that even if we raise the issue in another repo 'support' it would still be reflected in our 'Stackoverflow-Analysis' repo's closed issues section

**Comment by Asymtode712** [comment]
@sanjay-kv Also my contribution which was merged earlier in this repo for this issue is also valid, you just have to do 2 things:

- Create a custom label by the name "invite me to the community.
- Create a PAT(Personal Access Token) with the permissions: admin:org, user, repo and assign it to INVITE_TOKEN as the new environment secret.

Additionally,

- If a Error: 'Resource not accessible by integration' occurs then we would have to create another PAT with permissions: repo and assign it to PERSONAL_ACCESS as new environment secret and replace instances of 'GITHUB_TOKEN' with it.

**Comment by sanjay-kv** [comment]
> invite me to the community

https://github.com/Recode-Hive/Support/issues/labels

This is done.

**Comment by sanjay-kv** [comment]
> @sanjay-kv I tested the new workflow file and came to the conclusion that even if we raise the issue in another repo 'support' it would still be reflected in our 'Stackoverflow-Analysis' repo's closed issues section

That fine if it goes to closed PR

**Comment by sanjay-kv** [comment]
> @sanjay-kv Also my contribution which was merged earlier in this repo for this issue is also valid, you just have to do 2 things:
> 
> * Create a custom label by the name "invite me to the community".
> * Create a PAT(Personal Access Token) with the permissions: admin:org, user, repo and assign it to INVITE_TOKEN as the new environment secret.
> 
> Additionally,
> 
> * If a Error: 'Resource not accessible by integration' occurs then we would have to create another PAT with permissions: repo and assign it to PERSONAL_ACCESS as new environment secret and replace instances of 'GITHUB_TOKEN' with it.

I will fix the PAT tokens soon and update you.

**Comment by Asymtode712** [comment]
> > @sanjay-kv I tested the new workflow file and came to the conclusion that even if we raise the issue in another repo 'support' it would still be reflected in our 'Stackoverflow-Analysis' repo's closed issues section
> 
> That fine if it goes to closed PR

Correction: It would go to closed issues

**Comment by Asymtode712** [comment]
> > @sanjay-kv Also my contribution which was merged earlier in this repo for this issue is also valid, you just have to do 2 things:
> > 
> > * Create a custom label by the name "invite me to the community".
> > * Create a PAT(Personal Access Token) with the permissions: admin:org, user, repo and assign it to INVITE_TOKEN as the new environment secret.
> > 
> > Additionally,
> > 
> > * If a Error: 'Resource not accessible by integration' occurs then we would have to create another PAT with permissions: repo and assign it to PERSONAL_ACCESS as new environment secret and replace instances of 'GITHUB_TOKEN' with it.
> 
> I will fix the PAT tokens soon and update you.

Sure, take your time

**Comment by Asymtode712** [comment]
> > invite me to the community
> 
> https://github.com/Recode-Hive/Support/issues/labels
> 
> This is done. +Created PAT Tokens. need to assign to env secret. will do n confirm

You must create this in this particular repo as the issue would be raised from here

**Comment by Asymtode712** [comment]
@sanjay-kv I guess I have confused you a bit, let me explain you the whole scenario again and explain you have I tested the workflows:

1. Raise an issue from **Stackoverflow-Analysis** repo by selecting the invitation template.
2. Workflow would begin, check for the revelant label, if the label is matched it would take this issue to the **Support** repo and close it in **Stackoverflow-Analysis** repo which would be then reflected in Closed issues.
3. If the labels are not matched then the issue would remain in **Stackoverflow-Analysis** repo and workflow would be stopped.
4. Once the issue is transferred to **Support** repo's open issues, the further invitation workflow would be carried out

Now, invitation.yml template and invitation.yml workflow will still be in this repo

I guess this will help you

**Comment by Asymtode712** [comment]
@sanjay-kv Any updates??

Also, Ensure this so that you get rid of that integration error:

![allow workflow](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/115717746/9aa51740-da36-409c-97b1-f49388465e35)

**Comment by sanjay-kv** [comment]
are you up for a call: I kinda confused on the workflow area.

**Comment by Asymtode712** [comment]
@sanjay-kv sure

**Comment by sanjay-kv** [comment]
send you message on linkedin @Asymtode712
